### ISSUE TITLE
Write test to catch array length bug

### ISSUE THREAD

**Issue by wilt00** [wilt00/friendlydebug#9]
Several helpful and well-meaning people have now submitted pull requests for #1, but so far none of them have remembered to increment the constant `FDBG_NUMMESSAGES` to match the new length of ` __fdbg_messages`. I would like a test, compatible with Travis CI (which I've just set up) which would catch this common mistake.

**Comment by oktak** [comment]
Let me take this :D

**Comment by wilt00** [comment]
All yours, my dude!


________________________________

**Comment by wilt00** [comment]
Closed by #11.
